/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AdminImport } from './routes/_admin'
import { Route as IndexImport } from './routes/index'
import { Route as CatalogIndexImport } from './routes/catalog.index'
import { Route as SignInAdminImport } from './routes/sign-in.admin'
import { Route as CatalogSearchImport } from './routes/catalog.search'
import { Route as CatalogPlaceIdImport } from './routes/catalog.$placeId'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlannerImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedPlannerResultImport } from './routes/_authenticated/planner.result'
import { Route as AdminAdminDashboardImport } from './routes/_admin/admin.dashboard'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => rootRoute,
})

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
})

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
})

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
})

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
})

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
})

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
})

const CatalogIndexRoute = CatalogIndexImport.update({
  path: '/catalog/',
  getParentRoute: () => rootRoute,
})

const SignInAdminRoute = SignInAdminImport.update({
  path: '/admin',
  getParentRoute: () => SignInRoute,
})

const CatalogSearchRoute = CatalogSearchImport.update({
  path: '/catalog/search',
  getParentRoute: () => rootRoute,
})

const CatalogPlaceIdRoute = CatalogPlaceIdImport.update({
  path: '/catalog/$placeId',
  getParentRoute: () => rootRoute,
})

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
})

const AuthenticatedPlannerRoute = AuthenticatedPlannerImport.update({
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
})

const AuthenticatedPlannerResultRoute = AuthenticatedPlannerResultImport.update(
  {
    path: '/result',
    getParentRoute: () => AuthenticatedPlannerRoute,
  },
)

const AdminAdminDashboardRoute = AdminAdminDashboardImport.update({
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
})

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AdminRoute: AdminRoute.addChildren({ AdminAdminDashboardRoute }),
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedPlannerRoute: AuthenticatedPlannerRoute.addChildren({
      AuthenticatedPlannerResultRoute,
    }),
    AuthenticatedProfileRoute,
  }),
  AboutRoute,
  ContactRoute,
  SignInRoute: SignInRoute.addChildren({ SignInAdminRoute }),
  SignUpRoute,
  CatalogPlaceIdRoute,
  CatalogSearchRoute,
  CatalogIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/_admin",
        "/_authenticated",
        "/about",
        "/contact",
        "/sign-in",
        "/sign-up",
        "/catalog/$placeId",
        "/catalog/search",
        "/catalog/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/_admin": {
      "filePath": "_admin.jsx",
      "children": [
        "/_admin/admin/dashboard"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.jsx",
      "children": [
        "/_authenticated/planner",
        "/_authenticated/profile"
      ]
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/contact": {
      "filePath": "contact.jsx"
    },
    "/sign-in": {
      "filePath": "sign-in.jsx",
      "children": [
        "/sign-in/admin"
      ]
    },
    "/sign-up": {
      "filePath": "sign-up.jsx"
    },
    "/_authenticated/planner": {
      "filePath": "_authenticated/planner.jsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/planner/result"
      ]
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.jsx",
      "parent": "/_authenticated"
    },
    "/catalog/$placeId": {
      "filePath": "catalog.$placeId.jsx"
    },
    "/catalog/search": {
      "filePath": "catalog.search.jsx"
    },
    "/sign-in/admin": {
      "filePath": "sign-in.admin.jsx",
      "parent": "/sign-in"
    },
    "/catalog/": {
      "filePath": "catalog.index.jsx"
    },
    "/_admin/admin/dashboard": {
      "filePath": "_admin/admin.dashboard.jsx",
      "parent": "/_admin"
    },
    "/_authenticated/planner/result": {
      "filePath": "_authenticated/planner.result.jsx",
      "parent": "/_authenticated/planner"
    }
  }
}
ROUTE_MANIFEST_END */
